var reviewSchema = new mongoose.Schema({
  id: Number,
  custName: String,
  custPic: String,
  date: String,
  reviewText: String,
  accuracy: Number,
  location: Number,
  communication: Number,
  checkIn: Number,
  cleanliness: Number,
  value: Number,
  hostName: String,
  hostPic: String,
  responseText: String,
  roomId: Number,
  createdAt: Date.now(),
  updatedAt: Date.now(),
});